[models]
enable = ["preset:thinking", "preset:coding", "preset:free"]

[models.presets]
thinking = [
  "openai/o3-mini-high",
  "anthropic/claude-3.7-sonnet:thinking",
  "deepseek/deepseek-r1",
]
coding = [
  "openai/gpt-4o-mini",
  "openai/gpt-4o-2024-11-20",
  "openai/o3-mini-high",
  "anthropic/claude-3.7-sonnet",
  "anthropic/claude-3.7-sonnet:thinking",
  "deepseek/deepseek-chat-v3-0324",
  "google/gemini-2.0-flash-001",
  "google/gemini-2.5-pro-preview-03-25",
  "openrouter/quasar-alpha",
]
free = [
  "deepseek/deepseek-r1:free",
  "deepseek/deepseek-chat-v3-0324:free",
  "google/gemini-2.5-pro-exp-03-25:free",
]
