default_model = "deepseek/deepseek-chat-v3-0324:free"

[models]
enable = ["preset:programming", "preset:reasoning", "preset:free"]

[models.presets]
programming = [
  "anthropic/claude-sonnet-4",
  "google/gemini-2.5-flash",
  "qwen/qwen3-coder",
  "google/gemini-2.5-pro",
  "anthropic/claude-3.7-sonnet",
  "moonshotai/kimi-k2",
  "x-ai/grok-4",
  "anthropic/claude-opus-4",
  "qwen/qwen3-235b-a22b-2507",
  "deepseek/deepseek-chat-v3-0324",
]
reasoning = [
  "anthropic/claude-sonnet-4",
  "google/gemini-2.5-flash",
  "google/gemini-2.5-pro",
  "anthropic/claude-3.7-sonnet",
  "deepseek/deepseek-r1-0528:free",
  "google/gemini-2.5-flash-lite-preview-06-17",
  "anthropic/claude-opus-4",
  "deepseek/deepseek-r1:free",
  "x-ai/grok-4",
  "google/gemini-2.5-flash-lite",
]
free = [
  "deepseek/deepseek-chat-v3-0324:free",
  "qwen/qwen3-coder:free",
  "deepseek/deepseek-r1-0528:free",
  "qwen/qwen3-235b-a22b-2507:free",
  "deepseek/deepseek-r1:free",
  "tngtech/deepseek-r1t2-chimera:free",
  "moonshotai/kimi-k2:free",
  "tngtech/deepseek-r1t-chimera:free",
  "google/gemini-2.0-flash-exp:free",
  "qwen/qwen-2.5-72b-instruct:free",
]
